sonarr:
  url: "http://your-sonarr-url:8989"  # 替换为你的 Sonarr URL
  api_key: "your-sonarr-api-key"  # 替换为你的 Sonarr API 密钥

bangumi:
  user_id: 0  # 替换为你的 Bangumi 用户 ID

database:
  path: "/data/tvdb_cache.db"  # 使用持久化存储

cache:
  expire_days: 7  # 缓存过期天数

server:
  host: "0.0.0.0"
  port: 8990
  debug: false

log:
  level: "INFO"